export const dummyImages = [
  {
    _id: 'dummy1',
    type: 'image',
    mediaUrl: 'https://placekitten.com/400/400',
    isSensitive: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'dummy2',
    type: 'image',
    mediaUrl: 'https://placekitten.com/401/401',
    isSensitive: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'dummy3',
    type: 'image',
    mediaUrl: 'https://placekitten.com/402/402',
    isSensitive: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'dummy4',
    type: 'image',
    mediaUrl: 'https://placekitten.com/403/403',
    isSensitive: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'dummy5',
    type: 'image',
    mediaUrl: 'https://placekitten.com/404/404',
    isSensitive: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'dummy6',
    type: 'image',
    mediaUrl: 'https://placekitten.com/405/405',
    isSensitive: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'dummy7',
    type: 'image',
    mediaUrl: 'https://placekitten.com/406/406',
    isSensitive: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'dummy8',
    type: 'image',
    mediaUrl: 'https://placekitten.com/407/407',
    isSensitive: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'dummy9',
    type: 'image',
    mediaUrl: 'https://placekitten.com/408/408',
    isSensitive: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'dummy10',
    type: 'image',
    mediaUrl: 'https://placekitten.com/409/409',
    isSensitive: true,
    createdAt: new Date().toISOString(),
  },
];
