export const endpoints = {
  signup: 'api/auth/user',
  login: 'api/auth/login',
  userProfile: 'api/user/update-profile',
  userInfo: 'api/user/user-info',
  usernameAvailable: 'api/user/is-username-available',
  userContacts: 'api/user/messages/get-all-chats',
  searchUsers: 'api/user/search',
  sendFriendRequest: 'api/user/add-friend',
  friendRequests: 'api/user/friend-requests',
  rejectFriendRequest: 'api/user/reject-friend-request',
  conversations: 'api/user/one-to-one-chat',
  sendMessage: 'api/user/messages/send-message',
  uploadFile: 'api/user/upload-files',
  readChat: 'api/user/read-chat',
  checkContacts: 'api/user/check-contacts',
  suggestedUsers: 'api/user/suggested-users',
  userGallery: 'api/user/get-user-gallery',
  markAsSensitive: 'api/user/mark-as-sensitive',
  markAsUnsensitive: 'api/user/marks-as-unsensitive',
  deleteMessages: 'api/user/delete-messages',
};
